### ISSUE TITLE
Do not verify kubernetes apiserver cert

### ISSUE THREAD

**Issue by drpebcak** [Talend/vault-sidecar-injector#19] opened 2020-01-03 18:01 UTC
Using RKE, kubernetes is configured with self-signed certs that are trusted within the cluster. I need a way to tell the injected sidecar to NOT verify the certificate.

```
URL: PUT http://vault.vault.svc.cluster.local:8200/v1/auth/kubernetes/login
Code: 500. Errors:
* Post https://kubernetes.default.svc/apis/authentication.k8s.io/v1/tokenreviews: x509: certificate signed by unknown authority" backoff=2.035247216
2020-01-03T17:57:26.621Z [INFO] auth.handler: authenticating
2020-01-03T17:57:26.641Z [ERROR] auth.handler: error authenticating: error="Error making API request.
```

**Comment by asaintsever** [comment] 2020-01-04 14:35
Hi,

Problem is, this is not the injected sidecar (Vault Agent) that is performing the POST call you can see in the log output. Call to `https://kubernetes.default.svc/apis/authentication.k8s.io/v1/tokenreviews` is done by your **Vault Server** following Vault Agent login request, not by the Vault Agent itself. So this is not something we can control at the webhook or sidecar level.

However, it looks like this is something you can do on Vault Server side when you configure the Kubernetes Auth Method. See optional `pem_keys` parameter here: https://www.vaultproject.io/api/auth/kubernetes/index.html#pem_keys

Given the context, I will close this ticket as the issue is not related to the Vault Sidecar Injector component but is about Vault Server or Kubernetes configuration. Feel free to open a new ticket with detailed information if need be. Thanks.

**Closed by asaintsever** 2020-01-04 14:35 UTC

**Comment by drpebcak** [comment] 2020-01-05 00:13
Ah yes, I realized that this was an issue with the way I configured kubernetes auth for vault - I passed in the wrong CA cert. Thanks!
